### PR TITLE
Add notice comment to formatted code blocks

### LINKED ISSUE #3: Add a comment to the updated code
I think it would be great if you add a comment to the markdown which says that the code got formatted with prettier.

Input:
````md
```js
// some code
```
````

Output:
````md
<!-- We formatted your code with prettier.
Change this comment to "prettier-github disable" to disable automatic code formatting.
Learn more at https://github.com/jgierer12/prettier-github -->
```js
// some formatted code
```
````

This way only the author of the comment can see the comment if they try to remove the formatting. Probably add the original code in the comment as well.

What do you think?

### PR DESCRIPTION
**Pull request by jgierer12**
If `prettier-github` formats a code block, this will be noted in a comment, including instructions to disable the bot and the original code block.

For example, this:
````markdown
```js
foo(reallyLongArg(), omgSoManyParameters(), IShouldRefactorThis(), isThereSeriouslyAnotherOne());
```
````
will now be transformed into this:
````markdown
<!-- The following code block was formatted with `prettier`. If this is not desired, please change this comment to `prettier-github disable`. A copy of your original code block is included below in case you want to restore it.
Learn more about `prettier-github` at https://github.com/jgierer12/prettier-github

foo(reallyLongArg(), omgSoManyParameters(), IShouldRefactorThis(), isThereSeriouslyAnotherOne());

-->
```js
foo(
  reallyLongArg(),
  omgSoManyParameters(),
  IShouldRefactorThis(),
  isThereSeriouslyAnotherOne()
);
```
````

Closes #3 
@k15a does this look good?

### CODE REVIEW

**Comment by k15a** [comment]
That looks awesome. How does this behave if I change formatted code because I forgot something and github-prettier reformats the code?

**Comment by jgierer12** [comment]
Good point. Currently, it just adds another comment.

**Comment by k15a** [comment]
Probably should update the comment but I think that's not a priority as you can always remove the comments yourself :)

**Comment by jgierer12** [comment]
Alright, it now overrides old notice comments if they exist.

**Pull request merged**
